### PR TITLE
Rewrite package using TypeScript

### PR DESCRIPTION
**Pull request by SeinopSys**
Companion PR to issue #9 

I will say up front that I'm not sure how best to publish this to npm, but I figured this is a good starting point for it. The build command creates something that looks publishable to me but a second look would not hurt.

### CODE REVIEW

**Comment by SeinopSys** [comment]
*Oh.*

I'll get the docs folder TypeScript-ified then

**Comment by SeinopSys** [comment]
Update: This definitely does not seem to work, I tried symlinking the package folder to an existing project and importing fails. I'll keep looking into it, not sure how to mare this PR as WIP but don't merge it yet.

**Comment by luukdv** [comment]
Thanks so much for all your work on this. Like indicated in the related issue, TS is not really familiar territory for me. To be honest, I've read https://medium.com/javascript-scene/the-typescript-tax-132ff4cb175b at one point and haven't looked a lot at it since. I can see benefits though, but it might take a little while to get myself up to speed and grasp everything before this can be merged. Hope that's okay!

**Comment by luukdv** [comment]
I'll make sure not to merge it yet. At the moment it's not possible to mark PRs as drafts after they're published, but I've appended `[WIP]` to the title as an indicator.

**Comment by SeinopSys** [comment]
Alright, I might have been using an incorrect way to test it and it was also definitely broken, so the current version was tested via running the build, then installing the folder into another project and deleting the `node_modules` in the dependency's folder under said project, that way I was able to import it, types resolved and the project it was imported into also managed to build. I'm hopeful this should work as is.

**Comment by SeinopSys** [comment]
I tried to follow the changes in `master` but the generated output does not really look all that different between the two types of bundles, so I'm worried something might be amiss.

**Comment by luukdv** [comment]
Looking into it! I've also simplified some stuff. It's not done yet, still need to take a look at the docs folder.

**Pull request merged**
