### PR TITLE
Refactor & implement lineWidth

### LINKED ISSUE #28: Prop to set line-width
It would be great if there was a prop to set the line width. So something like this:

```
<Hamburger lineWidth={3} />
```

Keep up the epic work!! 💪😄

### PR DESCRIPTION
**Pull request by cyntler**
Closes #28 

- add .nvmrc files with Node v16
- move hamburger components to src/components
- add new prop `lineWidth`
- install & config Prettier for the project

### CODE REVIEW

**Comment by luukdv** [comment]
Thanks so much for the effort! I didn't know you had this planned… I've actually been working on version `3.0` that's quite an overhaul, which should solve other use cases as well (for example being able to control both `barWidth` and `barHeight` as described in https://github.com/luukdv/hamburger-react/issues/28).

**Comment by cyntler** [comment]
@luukdv Oh, okay! :) I understand. So in this situation I think we can close the pull request. I will wait for you changes! :)

**Comment by NeeshSamsi** [comment]
@luukdv Is there any progress on the 3.0? Would love to have the lineWidth prop added at some point. This is by far the best library I've found for effortless hamburger menus.

**Comment by luukdv** [comment]
Thank you! Update about v3.0: [Looking for new owner](https://github.com/luukdv/hamburger-react/issues/64)

**Pull request closed without merging**
